"""empty message

Revision ID: 60abbe717a92
Revises: 1651361309ed
Create Date: 2022-08-11 11:04:09.650298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60abbe717a92'
down_revision = '1651361309ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('work_site', sa.Unicode(length=50), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'work_site')
    # ### end Alembic commands ###
